### ISSUE TITLE
Unterminated Regular Expression Error except when comment on next line

### ISSUE THREAD

**Issue by jaydiablo** [douglascrockford/JSMin#10]
With the latest update to JSMin I was able to get it to minify the d3.js library correctly, thanks again for that.  So I decided to do a little work on the PHP port of JSMin to get it up to date with the latest release, however I ran into an inconsistency that I thought I would point out.

Once again, the d3 author(s) are doing something that JSLint doesn't recommend:

``` javascript
// Compute the angular scale factor: from value to radians.
var k = ((typeof endAngle === "function"
    ? endAngle.apply(this, arguments)
    : endAngle) - startAngle)
    / d3.sum(values);
```

Running JSMin on just this snippet will cause it to spit up the "Unterminated Regular Expression literal." due to the division operator being on its own line.  Which made me question why/how it's getting through the whole d3.js file without encountering the same error.  It appears to be because the next line in the file is a comment:

``` javascript
// Compute the angular scale factor: from value to radians.
var k = ((typeof endAngle === "function"
    ? endAngle.apply(this, arguments)
    : endAngle) - startAngle)
    / d3.sum(values);

// Optionally sort the data.
```

I believe that JSMin sees that first character of the comment line as the ending regex token, so doesn't complain in this situation.

**Comment by douglascrockford** [comment]
Thank you. Please try the latest.
