### ISSUE TITLE
c++ streambuf implementation

### ISSUE THREAD

**Issue by AndreasSchoenle** [douglascrockford/JSMin#17]
I needed a quick and dirty implementation to clean .json files from comments and created a streambuf based version of jsmin. The code is not nice nor clean and it is not very well tested as we are not using it in production but maybe someone will find the implementation useful as a starting point. 

It can be found [here](https://github.com/AbberiorInstruments/jsminstream).

**Comment by douglascrockford** [comment]
Please make it nice and clean, well tested, and ready for production.
