### ISSUE TITLE
Regular expression literal can have its whitespace removed

### ISSUE THREAD

**Issue by li-a** [douglascrockford/JSMin#19]
Consider this legal JS (found in highcharts 4.1.4, already apparently minified by Closure Compiler):

```{dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN| {2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a}}```

JSMin outputs:

```{dSetter:function(a,b,c){a&&a.join&&(a=a.join(" "));/(NaN|{2}|^$)/.test(a)&&(a="M 0 0");c.setAttribute(b,a);this[b]=a}}```

The RegExp literal has been modified (`| {` --> `|{`, which also happens to be invalid syntax).

Seems to be distinct from #11 because testing across history indicates the problem was only introduced by cec896f0affaa0226c02605ad28d42df1bc0e393 (which is newer than #11).

**Comment by douglascrockford** [comment]
A problem I have had historically is that if one of my tools accepts code that is badly written, then it is assumed that 'I' am approving, which I am not. That is why made that change in 2012. Up until now, no one has complained.

There is a lot of stupid stuff happening in that highcharts code, but I am past caring about it. JSMin will now accept it.

**Comment by li-a** [comment]
Thanks for looking. The "bad code" here is output from minification, not meant for human consumption. Highcharts source happens to look friendlier:
```
if (/(NaN| {2}|^$)/.test(value)) {
	value = 'M 0 0';
}
```
(and minifies fine w/ JsMin).

Ugliness or other badness aside, as far as I can tell, the JsMin input here is valid ES 3 and the output is not. We have an easy workaround for this one, but we believe this hits many codebase files that are not highcharts.

I didn't realize JsMin was being maintained, and we have seen the usage warning/caveats, but I filed this in case someone else is searching around. Will post a fix if we make one.

**Comment by li-a** [comment]
Some simplified failure cases:

- `;/a# b/;`  -->  `;/a#b/;`
- `;/a| b/;`  -->  `;/a|b/;`
- `;/# /;`  -->  `;/#/;`
- `;/| /;` --> Error: Unterminated regular expression at line 0 and column 7

The leading semicolon seems to be significant.

**Comment by douglascrockford** [comment]
I think this is fixed in the latest.

Why are you minifying minified code?

**Comment by li-a** [comment]
Confirmed all our cases are resolved. I didn't notice changes went in, thanks for looking.

The double minification fix is planned.
