### ISSUE TITLE
Jsmin doesn't treat backtick strings as strings

### ISSUE THREAD

**Issue by Lazerbeak12345** [douglascrockford/JSMin#23]
A string such as this:

```js
var subUrl = prompt("hi"),
  myVar = `https://example.com/${subUrl}/moreurlstuff`
console.log(myVar)
```

Is turned into something like this:

```js
var subUrl=prompt("hi"),myVar=`https:console.log(myVar)
```

In other words it causes a syntax error (unterminated backtick string starting at char 31. The double forward slash in the original string is treated as a single-line comment). For other people having this _exact_ issue, a temporary workaround was to change the code to this untill jsMin can handle backtick strings, but I can't say for sure if this would cause other problems as I have yet to try it in prod with more compicated strings.

```js
var subUrl = prompt("hi"),
  myVar = `https:/${"/"}example.com/${subUrl}/moreurlstuff`
console.log(myVar)
```

**Comment by Lazerbeak12345** [comment]
It's odd though, in [line 152][L152] and in [line 288][L228] it looks like it _does_ have support for these strings: in fact it seems to be treating them as any other string. Perhaps the issue is in the `next` function when it removes comments?

[L152]: https://github.com/douglascrockford/JSMin/blob/7d7aea259acaa8fe61d09d168a004ed9a8dd072a/jsmin.c#L152
[L228]: https://github.com/douglascrockford/JSMin/blob/7d7aea259acaa8fe61d09d168a004ed9a8dd072a/jsmin.c#L288

**Comment by louking** [comment]
I'm seeing the same problem, just came looking for this here.

```
          d3.select(`.tablerow-${year} .date`).text(`${formatDate(d.date)}/${year}`);
          d3.select(`.tablerow-${year} .count`).text(d.count);
```

is getting translated to

```
d3.select(`.tablerow-${year}.date`).text(`${formatDate(d.date)}/${year}`);d3.select(`.tablerow-${year}.count`).text(d.count);
```

Note the spaces missing before `.date` and `.count` in the two statements

**Comment by douglascrockford** [comment]
Are you using the lastest (2019-10-30)?

JSMIN treats '`' exactly the same as '"'. It will get confused if you nest '`' inside of '${}' expressions, but humans do too, so I don't recommend doing that.

Have a happier 2022.

**Comment by Lazerbeak12345** [comment]
Keep in mind the difference between `\`` strings and `\'` strings here... I think this is the problem.

**Comment by Lazerbeak12345** [comment]
In the code that I encountered, only part of it was under my control - the rest in a proprietary WordPress plugin. You can't always choose how the code looks, or what semantics it uses.

**Comment by douglascrockford** [comment]
It seems that you are using a version of JSMIN from the time before backtick was added to JavaScript.

**Comment by Lazerbeak12345** [comment]
@timeclicky You might want to take it from here... (since I don't work for timeclick anymore....)
