### ISSUE TITLE
Over eager removal of whitespace

### ISSUE THREAD

**Issue by TracyGJG** [douglascrockford/JSMin#26]
In the majority of cases any whitespace following the closing curly brace can be removed but since the introduction of template literals this is no longer a safe assumption. Spaces following interpolated values in a template literal need to be preserved. For example,
``Unexpected ${token} encountered`` gets incorrectly minified to ``Unexpected ${token}encountered`` so when the token is 'comma' the minified version outputs 'Unexpected commaencountered'.

**Comment by douglascrockford** [comment]
It works for me. Can you please provide a minimal test case that passes JSLint?

**Comment by TracyGJG** [comment]
Not sure how this issue can be dismissed so easily so here is a minimal example using jsmin 1.0.1 from npm:

```js
const token = "String";
const message = `Unexpected ${token} encountered`;
```

The result of running JSMin:

```js
const token="String";const message=`Unexpected ${token}encountered`;
```

Observe how the space after the closing curly brace in the template literal has been removed, which changes the value of `message`.

Environment: MS Windows 11 home, Node Js 18.12.1

I ran the code through JSLint.com without a fault.

**Comment by douglascrockford** [comment]
I have never put anything on npm. I think it is likely that the version you are using was written a decade before `` was proposed.

**Comment by TracyGJG** [comment]
Thanks. I have submitted the issue with the [node-jsmin repo](https://www.npmjs.com/package/jsmin) that is commonly known and used just as jsmin, thus the confusion.
